### ISSUE TITLE
trezorCipherKeyValue and systemd-ask-password

### ISSUE THREAD

**Issue by pontostroy** [xaionaro-go/trezorCipherKeyValue#2]
Looks like  systemd-ask-password does not work

echo luks | /home/pontostroy/GO/GOPATH/bin/trezorCipherKeyValue -p "/usr/bin/systemd-ask-password" -e -k luks

Password entry required for 'PIN' (PID 7541).
Please enter password with the systemd-tty-ask-password-agent tool!
3443
82987694
70741

I can't entered my pin, pressing the ernter button leads to a new line.

**Comment by xaionaro** [comment]
First of all, `systemd-ask-password` answered:

> Please enter password with the systemd-tty-ask-password-agent tool!

it means that `systemd-ask-password` expects you to run `systemd-tty-ask-password-agent` tool and enter the password there.

The second you're trying to pass both key and passphrase via one stdin. I don't understand how to implement this correctly on the utility side (to understand which of the stdin data is for what), so you should use one of this options:
* Use GUI-based askpass/pinentry.
* Or pass the key via environment variable `TREZOR_CIPHER_VALUE`.

The third, yes: `systemd-ask-password` requires a terminal (what wasn't implemented earlier), fixed. Should work if you consider the first two problems above.

An example:
```
TREZOR_CIPHER_VALUE=luks `go env GOPATH`/bin/trezorCipherKeyValue -e -k luks
```
